acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: puzzle
      replicaCount: 1
      image:
        repository: quay.io/acend/quarkus-techlab
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        emptyTLS: true
        ingressClassName: openshift-public
        useDefaultSecret: true
        labels:
          public: "true"
        appname: quarkus-techlab
        domainmain: puzzle.ch
        domain: ocp.cloudscale.puzzle.ch
    -
      name: mobi
      replicaCount: 1
      image:
        repository: quay.io/acend/quarkus-techlab
        pullPolicy: Always
        tag: ""
        tagsuffix: "-mobi"
      ingress:
        emptyTLS: true
        ingressClassName: openshift-public
        useDefaultSecret: true
        labels:
          public: "true"
        appname: quarkus-techlab-mobi
        domainmain: ocp.cloudscale.puzzle.ch
        domain: ocp.cloudscale.puzzle.ch


nameOverride: "quarkus-techlab"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
