apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pipeline-run-template
  annotations:
    description: 'Template to create project specific PipelineRuns.'
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: build-and-deploy-run-
    labels:
      tekton.dev/pipeline: build-and-deploy
    name: build-and-deploy-run-1
  spec:
    params:
    - name: deployment-name
      value: data-transformer
    - name: docker-file
      value: src/main/docker/Dockerfile.binary
    - name: git-revision
      value: master
    - name: git-url
      value: https://github.com/puzzle/quarkus-techlab-data-transformer.git
    - name: image-name
      value: image-registry.openshift-image-registry.svc:5000/${PROJECT_NAME}/data-transformer:latest
    - name: manifest-dir
      value: src/main/openshift/templates
    pipelineRef:
      name: build-and-deploy
    serviceAccountName: pipeline
    timeout: 1h0m0s
    workspaces:
    - name: source-workspace
      persistentVolumeClaim:
        claimName: pipeline-workspace
parameters:
- description: OpenShift Project Name
  name: PROJECT_NAME
  required: true
